apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-example-config
data:
  WP_HOME: https://dev.example.com
  WP_SITEURL: https://dev.example.com
  TABLE_PREFIX: wp_
  WP_CONTENT_DIR: /var/www/example.com/wp-content
  FS_METHOD: direct
  WP_DEBUG: "true"
  WP_DEBUG_LOG: "true"
  WP_DEBUG_DISPLAY: "false"
  WP_POST_REVISIONS: "3"
  DB_HOST: wordpress-mysql
  DB_NAME: dev_example
  DB_CHARSET: utf8mb4
  DB_COLLATE: ""

