apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-example-wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: dev-example-wordpress-pvc
    namespace: main
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: dev-example-wordpress
    fsType: ext4