apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: example-wordpress-pvc
    namespace: main
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: example-wordpress
    fsType: ext4