apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "example"