apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: mysql-pvc
    namespace: main
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: example-mysql
    fsType: ext4